apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: campus-cloud-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dhaifulloh/campus-cloud-lab.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: campus-cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true